<a href="https://colab.research.google.com/github/ganeshwadule/Machine-Learning-Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.arange(10)

In [3]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
A.shape

(10,)

In [5]:
B = np.random.randint(0,10,(1,10))

In [6]:
B.shape

(1, 10)

In [7]:
B

array([[5, 9, 7, 6, 8, 8, 2, 5, 0, 1]])

In [8]:
A= A[np.newaxis,:]

In [9]:
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
A.shape

(1, 10)

In [12]:
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
B

array([[5, 9, 7, 6, 8, 8, 2, 5, 0, 1]])

In [14]:
np.add(A,B)

array([[ 5, 10,  9,  9, 12, 13,  8, 12,  8, 10]])

In [15]:
A.sum()

45

In [16]:
np.sum(A)

45

In [45]:
matrix = np.arange(100).reshape(2,2,5,5)

In [46]:
matrix

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

In [50]:
matrix.shape

(2, 2, 5)

In [51]:
matrix = matrix.sum(axis=0)


In [52]:
matrix

array([[270, 320, 370, 420, 470],
       [520, 570, 620, 670, 720]])

In [30]:
matrix.shape

(2, 2)